<project xmlns="http://maven.apache.org/POM/4.0.0"
		 xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>pt.tecnico.sdis.2025.A19</groupId>
	<artifactId>Front-End</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>jar</packaging>
	<name>${project.artifactId}</name>

	<!-- Properties are variables used to customize the behavior of Maven and its plugins. -->
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<version.java>17</version.java>
		<version.maven-compiler-plugin>3.8.1</version.maven-compiler-plugin>
		<version.exec-maven-plugin>3.0.0</version.exec-maven-plugin>

		<mainclass>pt.ulisboa.tecnico.tuplespaces.frontend.FrontEndServer</mainclass>
		<server.hostport>localhost:3001</server.hostport>
		<client.id>1</client.id>
	</properties>

	<dependencies>
		<!-- Dependency for the Contract (gRPC contract) -->
		<dependency>
			<groupId>pt.tecnico.sdis.2025.A19</groupId>
			<artifactId>Contract</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>

		<!-- Dependency for both client and server (shared dependency with the server) -->
		<dependency>
			<groupId>pt.tecnico.sdis.2025.A19</groupId>
			<artifactId>SingleServer</artifactId>
			<version>1.0.0-SNAPSHOT</version>
		</dependency>

		<!-- gRPC dependencies for both client and server -->
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-netty-shaded</artifactId>
			<version>1.48.0</version>
		</dependency>
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-protobuf</artifactId>
			<version>1.48.0</version>
		</dependency>
		<dependency>
			<groupId>io.grpc</groupId>
			<artifactId>grpc-stub</artifactId>
			<version>1.48.0</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<!-- Plugin for compiling the source code -->
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${version.maven-compiler-plugin}</version>
				<configuration>
					<source>${version.java}</source>
					<target>${version.java}</target>
				</configuration>
			</plugin>

			<!-- Plugin for executing Java code -->
			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>${version.exec-maven-plugin}</version>
				<executions>
					<execution>
						<goals>
							<goal>java</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<mainClass>${mainclass}</mainClass>
					<arguments>
						<argument>${server.hostport}</argument>
						<argument>${client.id}</argument>
					</arguments>
				</configuration>
			</plugin>
		</plugins>
	</build>

</project>
